name 'rajtest'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures rajtest'
long_description 'Installs/Configures rajtest'
version '0.1.0'
