name 'awstest'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures awstest'
long_description 'Installs/Configures awstest'
version '0.1.0'
